development:
  adapter: redis
  url: "redis://onebitmessenger.web7081.uni5.net:6379"
  channel_prefix: one_bit_messenger_production

test:
  adapter: test

production:
  adapter: redis
  url: "redis://onebitmessenger.web7081.uni5.net:6379"
  channel_prefix: one_bit_messenger_production
